## Creating Numpy Arrays

In [4]:
# np.array
import numpy as np


In [5]:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


### Creating 2D and 3D numpy array

#### A. 2D Numpy array

In [6]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


#### B. 3D Numpy array

In [7]:
c = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Making our own datatype

In [8]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [9]:
np.array([0,1,2,3,4,40], dtype=bool)

array([False,  True,  True,  True,  True,  True])

In [10]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

### Making array range

In [11]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,11.-1)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

#### With Reshape

In [14]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [15]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

We will use arange function with conjunction of reshape function

### np.ones and np.zeros

In [16]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.random

In [18]:
np.random.random((3,4)) #It will generate random numbers between 0 and 1s and that will be any numbers.

array([[0.18415898, 0.05730513, 0.18727523, 0.24385958],
       [0.52591364, 0.47762656, 0.22160766, 0.6218616 ],
       [0.41342437, 0.37692263, 0.95819332, 0.86903815]])

In [19]:
np.random.random((4,4))

array([[0.74637147, 0.76542309, 0.22023459, 0.25287905],
       [0.72594857, 0.51808518, 0.81913394, 0.36698578],
       [0.36637918, 0.96689437, 0.53931406, 0.93021456],
       [0.62802027, 0.66245942, 0.43301213, 0.16209655]])

### np.linspace (Linearly spaced)


In [20]:
np.linspace(-10, 10, 10) #in brackets (Lower range, Upper range, number of items you want to generate) aso it generates linearly
                         #seperable points

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [21]:
np.identity(3) #identity is used in numpy function as np.identity() the working of this function is it prints the identity matrix.
               #In identity matrix there are 1s in the diaognal and zeros on the sides

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
a = int(input("Enter Low range number(negative number):"))
print(end = "\n")
b = int(input("Enter upper range number(Positive number):"))
print(end = "\n")
c = int(input("enter a number for your genererating items:"))
print(end = "\n")

print("Lower range number is:", a, "upper range number is:", b, "Generating numbers is:", c)
print(end = "\n")

d = np.linspace(a, b, c)
print(d)


Enter Low range number(negative number):-10

Enter upper range number(Positive number):11

enter a number for your genererating items:69

Lower range number is: -10 upper range number is: 11 Generating numbers is: 69

[-10.          -9.69117647  -9.38235294  -9.07352941  -8.76470588
  -8.45588235  -8.14705882  -7.83823529  -7.52941176  -7.22058824
  -6.91176471  -6.60294118  -6.29411765  -5.98529412  -5.67647059
  -5.36764706  -5.05882353  -4.75        -4.44117647  -4.13235294
  -3.82352941  -3.51470588  -3.20588235  -2.89705882  -2.58823529
  -2.27941176  -1.97058824  -1.66176471  -1.35294118  -1.04411765
  -0.73529412  -0.42647059  -0.11764706   0.19117647   0.5
   0.80882353   1.11764706   1.42647059   1.73529412   2.04411765
   2.35294118   2.66176471   2.97058824   3.27941176   3.58823529
   3.89705882   4.20588235   4.51470588   4.82352941   5.13235294
   5.44117647   5.75         6.05882353   6.36764706   6.67647059
   6.98529412   7.29411765   7.60294118   7.91176471   8.220588

## Array Attributes

In [25]:
a1 = np.arange(10)
a2= np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

### ndim

In [26]:
a1.ndim #the ndim stands for number of dimensions. It is used for to print how many dimensions the specific array have

1

In [27]:
a2.ndim

2

In [28]:
a3.ndim

3

### Shape

In [29]:
a1.shape #this will tell us that how many items are present in every dimension
         #Also it tells us that it is a 1D array and it has 10 items

(10,)

In [30]:
a2.shape

(3, 4)

In [31]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [32]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [33]:
a3.shape

(2, 2, 2)

### Size

In [34]:
a1.size

10

In [35]:
a2.size


12

In [36]:
a3.size

8

In [37]:
print("Number of dimensions in a1 is;", a1.ndim)
print("Shape of a1 is;", a1.shape)
print("Size of a1 is;", a1.size)

print(end = "\n")

print("Number of dimensions in a1 is;", a2.ndim)
print("Shape of a1 is;", a2.shape)
print("Size of a1 is;", a2.size)

print(end = "\n")

print("Number of dimensions in a1 is;", a3.ndim)
print("Shape of a1 is;", a3.shape)
print("Size of a1 is;", a3.size)

Number of dimensions in a1 is; 1
Shape of a1 is; (10,)
Size of a1 is; 10

Number of dimensions in a1 is; 2
Shape of a1 is; (3, 4)
Size of a1 is; 12

Number of dimensions in a1 is; 3
Shape of a1 is; (2, 2, 2)
Size of a1 is; 8


### Item size

In [38]:
a1.itemsize #It will tell us what the size of some specific items

8

In [39]:
a2.itemsize


8

In [40]:
a3.itemsize

8

### dtype

In [41]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [42]:
print("Number of dimensions in a1 is;", a1.ndim)
print("Shape of a1 is;", a1.shape)
print("Size of a1 is;", a1.size)
print("Item size of a1 is;", a3.shape)
print("Size of a1 is;", a3.size)

print(end = "\n")

print("Number of dimensions in a2 is;", a2.ndim)
print("Shape of a2 is;", a2.shape)
print("Size of a2 is;", a2.size)
print("Item Size of a2 is;", a3.shape)
print("Data type of a2 is;", a3.size)

print(end = "\n")

print("Number of dimensions in a3 is;", a3.ndim)
print("Shape of a3 is;", a3.shape)
print("Size of a3 is;", a3.size)
print("Item Size of a3 is;", a3.shape)
print("Data type of a3 is;", a3.size)




Number of dimensions in a1 is; 1
Shape of a1 is; (10,)
Size of a1 is; 10
Item size of a1 is; (2, 2, 2)
Size of a1 is; 8

Number of dimensions in a2 is; 2
Shape of a2 is; (3, 4)
Size of a2 is; 12
Item Size of a2 is; (2, 2, 2)
Data type of a2 is; 8

Number of dimensions in a3 is; 3
Shape of a3 is; (2, 2, 2)
Size of a3 is; 8
Item Size of a3 is; (2, 2, 2)
Data type of a3 is; 8


### Changing Data Types

In [43]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [44]:
a3.dtype

dtype('int64')

In [45]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations


In [46]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [47]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Scalar Operations

##### Arithmetc Operations

In [49]:
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [50]:
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [51]:
a1 / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [52]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

#### Relational operator

In [53]:
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [54]:
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [55]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

#### Vector Operations


##### Arithmetc Operation

Any operation between any two numpy arrays is done in vector operations


In [56]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [57]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [58]:
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [59]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [60]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

In [61]:
a1

array([[82., 40., 19.],
       [45., 43., 85.],
       [57., 30.,  1.]])

#### Max/Min/Sum/Prod

##### MAX


In [62]:
a1

array([[82., 40., 19.],
       [45., 43., 85.],
       [57., 30.,  1.]])

In [63]:
np.max(a1)

np.float64(85.0)

In [64]:
np.min(a1)

np.float64(1.0)

In [65]:
np.prod(a1)

np.float64(17527640220000.0)

In [66]:
np.sum(a1)

np.float64(402.0)

In [67]:
np.max(a1, axis = 1) # we are doing to find row wise maximum numbers. It will tell us in which row there is a maximum number

array([82., 85., 57.])

In [68]:
np.max(a1, axis = 0)

array([82., 43., 85.])

In [69]:
np.min(a1, axis = 0)

array([45., 30.,  1.])

In [70]:
np.min(a1, axis = 1)

array([19., 43.,  1.])

#### Mean/Median/Std/Var

##### Mean

In [71]:
np.mean(a1)

np.float64(44.666666666666664)

In [72]:
np.mean(a1, axis = 0)

array([61.33333333, 37.66666667, 35.        ])

In [73]:
np.mean(a1, axis = 1)

array([47.        , 57.66666667, 29.33333333])

##### Median

In [74]:
np.median(a1, axis = 1)

array([40., 45., 30.])

In [75]:
np.median(a1, axis = 0)

array([57., 40., 19.])

##### Standard Deviation

In [76]:
np.std(a1, axis = 1)

array([26.19160171, 19.34482417, 22.86676385])

In [77]:
np.std(a1, axis = 0)

array([15.41283736,  5.55777733, 36.11094017])

##### Variance

In [78]:
np.var(a1, axis = 1)

array([686.        , 374.22222222, 522.88888889])

In [79]:
np.var(a1, axis = 0)


array([ 237.55555556,   30.88888889, 1304.        ])

##### Trignometric Functions


###### Sin function


In [80]:
np.sin(a1)

array([[ 0.31322878,  0.74511316,  0.14987721],
       [ 0.85090352, -0.83177474, -0.17607562],
       [ 0.43616476, -0.98803162,  0.84147098]])

###### Cos Function


In [81]:
np.cos(a1)

array([[ 0.9496777 , -0.66693806,  0.98870462],
       [ 0.52532199,  0.5551133 , -0.98437664],
       [ 0.89986683,  0.15425145,  0.54030231]])

###### Tan Function

In [82]:
np.tan(a1)

array([[ 0.32982641, -1.11721493,  0.15158947],
       [ 1.61977519, -1.49838734,  0.17887017],
       [ 0.48469923, -6.4053312 ,  1.55740772]])

#### Dot Product


In [83]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [84]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [86]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

#### Log and Exponent

##### log


In [87]:
np.log(a1)

array([[4.40671925, 3.68887945, 2.94443898],
       [3.80666249, 3.76120012, 4.44265126],
       [4.04305127, 3.40119738, 0.        ]])

##### Exp

In [88]:
np.exp(a1)

array([[4.09399696e+35, 2.35385267e+17, 1.78482301e+08],
       [3.49342711e+19, 4.72783947e+18, 8.22301271e+36],
       [5.68572000e+24, 1.06864746e+13, 2.71828183e+00]])

#### Round/Floor/Ceil

##### Round

In [89]:
np.round(np.random.random((2,3))*100)

array([[37., 58., 78.],
       [55., 23., 41.]])

##### Floor

In [90]:
np.floor(np.random.random((2,3))*100)


array([[79., 84., 60.],
       [29., 90., 97.]])

##### Ceil

In [91]:
np.ceil(np.random.random((2,3))*100)

array([[60., 14., 92.],
       [92., 79., 39.]])

#### Indexing & Slicing


In [92]:
a1 = np.arange(10)

In [93]:
a2 = np.arange(12).reshape(3,4)

In [94]:
a3 = np.arange(8).reshape(2,2,2)

In [95]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

##### Idexing

In [96]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
a1[-1]

np.int64(9)

In [98]:
a1[0]

np.int64(0)

In [99]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
a2[1,2]

np.int64(6)

In [101]:
a2[2,3]

np.int64(11)

In [102]:
a2[1,0]

np.int64(4)

In [103]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [104]:
a3[1,0,1]

np.int64(5)

In [105]:
a3[0,0,0]

np.int64(0)

In [106]:
a3[0,1,0]

np.int64(2)

##### Slicing


In [107]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
a1[2:5]

array([2, 3, 4])

In [109]:
a1[2:5:2]

array([2, 4])

In [110]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
a2[0]

array([0, 1, 2, 3])

In [112]:
a2[0,:]

array([0, 1, 2, 3])

In [113]:
a2[:,2]

array([ 2,  6, 10])

#### Iterating


In [114]:
 a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [117]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [118]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [119]:
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [120]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7


#### Reshaping

##### Reshape

##### Transpose

In [121]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [123]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

##### Ravel

Any Dimention is it 2d or 3D anyone convert it into 1 D

In [124]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [125]:
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

#### Stacking

##### Horizontal Stacking

In [126]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [127]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [131]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [132]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

##### Vertical Stacking

In [134]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [137]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [138]:
np.vstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Splitting


##### Horizontal Splitting


In [140]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [143]:
np.hsplit(a4,2) #(a4,2) means a4 is the matrix and 2 is the number of splits

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [144]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [148]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

Vertical Splitting

In [149]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [152]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]